### ISSUE TITLE
Review hover effects on buttons

### ISSUE THREAD

**Issue by burnwatt** [capitalbr/indiedodo#11]
Check hover effects on splash/session form buttons

**Comment by capitalbr** [comment]
I've updated the featured carousel to mimic indiegogos

- clicking the image anywhere redirects to the show page

- The 'SEE CAMPAIGN' underlines on hover

- Added cursor: pointer; to buttons

**Comment by capitalbr** [comment]
I've fixed all remaining issues involving hover effects on those three pages.  Also made the news articles clickable.
