### ISSUE TITLE
If Time Before Friday:  Login/Register components convert to modals.

### ISSUE THREAD

**Issue by capitalbr** [capitalbr/indiedodo#22]
I'll definitely do this as a future addition but hopefully will get time to it before this weekend.

**Comment by burnwatt** [comment]
#6 Also covers this. I'll set it to you.

**Comment by burnwatt** [comment]
Sorry I didn't realize you had this issue tied to your project. I'll close the other one.

**Comment by capitalbr** [comment]
haha didn't mean to cause trouble

**Comment by capitalbr** [comment]
It's finished.  Just need to port over register styling to login and fix navbar session buttons styling (since they are now buttons instead of links)

**Comment by capitalbr** [comment]
Everything is finished now.
